#!/bin/sh

main()
{
	test ${#} -ne 2 && usage

	local tfile="${2}"

	auin="${1}"
	total="$(wc -l < "${tfile}" | awk '{print $1}')"
	ext="${1#*.}"

	read -erp "Album/book title: " album
	read -erp "Artist/author: " author
	read -erp "Publication year: " year

	albumdir="$(fmt_name "${album}")"
	mkdir -p "${albumdir}" || exit 1

	while read -r line; do
		end="$(echo "${line}" | cut -d' ' -f1)"
		test -n "${start}" && split_file
		title="$(echo "${line}" | cut -d' ' -f2-)"
		titlefmt="$(fmt_name "${title}")"
		track="$((track + 1))"
		start="${end}"
	done < "${tfile}"

	# The last track must be done outside the loop.
	split_file
}

usage()
{
	echo "usage: ${0##*/} audio timecode_file" 1>&2
	exit 1
}

fmt_name()
{
	echo "${1}" | iconv -cf UTF-8 -t ASCII//TRANSLIT |
	tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' |
	sed "s/-\+/-/g;s/\(^-\|-\$\)//g"
}

split_file()
{
	echo "From ${start} to ${end}; ${track} ${title}"
	echo "Splitting \"${title}\"..."
	ofile="${albumdir}/$(printf "%.2d" "${track}")-${titlefmt}.${ext}"
	ffmpeg \
		-nostdin -y -loglevel -8 \
		-i "${auin}" \
		-ss "${start}" \
		`test ${track} -eq ${total} || echo "-to ${end}"` \
		-vn -c copy \
		-map 0 \
		-metadata title="${title}" \
		-metadata album="${album}" \
		-metadata artist="${author}" \
		-metadata track="${track}/${total}" \
		-metadata date="${date}" \
		"${ofile}"
}

main "${@}"
