#!/bin/sh

# XXX: make this an env variable?
BMK_DIR="${HOME}/n/bookmarks/"

bmk_getfile()
{
	bmkfile="${BMK_DIR}"

	while [ -d ${bmkfile} ]; do
		bmkfile="$(
			find ${bmkfile} -maxdepth 1 |
			sed 1d |
			sort |
			dmenu -i -l 10 -p "Choose a file"
		)" || exit 1
	done
	test -f ${bmkfile} || exit 1
}

bmk_add()
{
	local url=$(xclip -o)

	if grep -q "^${url}" ${bmkfile}; then
		echo "Already bookmarked" | nfy
	else
		printf "%s\t%s\n" \
			"${url}" "$(dmenu -p "Bookmark name" </dev/null)" >> \
			${bmkfile}
		echo "Bookmark added" | nfy
	fi
}

bmk_fmt()
{
	for i in $(find ${BMK_DIR} | sed 1d); do
		sed 's/   */\t/' < ${i} | column -ts $'\t' > ${i}.tmp
		mv -f ${i}.tmp ${i}
	done
}

while getopts "af" arg; do
case "${arg}" in
	a)	bmk_getfile
		bmk_add
		bmk_fmt
		exit 0 ;;
	f)	bmk_fmt
		exit 0 ;;
	*)	echo "usage: ${0##*/} [-af]" 1>&2
		exit 1 ;;
esac
done

bmk_getfile

cat ${bmkfile} | dmenu -i -l 50 | awk '{print $1}' |
xargs -r xdotool type --delay 0
