#!/bin/sh

usage()
{
	echo "usage: ${0##*/} file" 1>&2 && exit 1
}

file_exists()
{
	test ! -f "${file}" && echo "${0##*/}: ${file}: file not found" 1>&2 && exit 1
}

test ${#} -eq 0 && usage

file="$(readlink -f "${1}")"
dir="${file%/*}"
base="${file%.*}"
ext="${file##*.}"

file_exists
cd "${dir}" || exit 1

case "${ext}" in
	md)	pandoc ${file} --pdf-engine=xelatex -V mainfont=Arial -o "${base}.pdf" ;;
	tex)	pdflatex ${file} ;;
		#rm -f *.aux *.log *.out *.bcf *.run.xml *.bbl *.blg *-blx.bib ;;
esac
