#!/bin/sh

usage()
{
	echo "usage: ${0##*/} file" 1>&2 && exit 1
}

test ${#} -eq 0 && usage
base="${1%.*}"
ext="${1##*.}"

case "${ext}" in
	html) setsid -f "${BROWSER}" "${base}.html" ;;
	tex|md) setsid -f xdg-open "${base}.pdf" ;;
esac
