#!/bin/sh

echo "mapaddress 10.40.40.40 libera75jm6of4wxpxt4aynol3xjmbtxgfyjpu34ss4d7r7q2v5zrpyd.onion" >> /usr/local/etc/tor/torrc
service tor restart
mkdir -p ~/.irssi/certs && cd ~/.irssi/certs
openssl req -x509 -sha256 -new -newkey rsa:4096 -days 1000 -nodes -out libera.crt -keyout libera.key
cat libera.crt libera.key > ~/.irssi/certs/libera.pem
chmod 600 libera.pem
rm libera.key libera.crt
printf "/msg NickServ CERT ADD "
openssl x509 -in ~/.irssi/certs/libera.pem -outform der | sha1 | cut -d' ' -f1
echo "/network add -sasl_username cmrg -sasl_password cmrgsasl -sasl_mechanism EXTERNAL LiberaTor"
echo "/server add -ssl -ssl_cert ~/.irssi/certs/libera.pem -net LiberaTor 10.40.40.40 6697"
echo "/ignore * CTCPS"
echo "/save"
echo "/quit"
