#!/bin/sh

MTPT="/mnt/droid"
f_umnt=0

while getopts u arg; do
case "${arg}" in
	u) f_umnt=1 ;;
	*) echo "usage: ${0##*/} [-u]" 1>&2 && exit 1 ;;
esac
done

test -z $(jmtpfs -l | sed 1d) && echo "No devices found" | nfy && exit 1
devno=$(jmtpfs -l | sed 1d | dmenu -i -p "Available devices" | cut -f1 -d':')
if [ ${f_umnt} -ne 1 ]; then
	mkdir -p "${MTPT}/${n}"
	jmtpfs --device "${n}" -o allow_other "${MTPT}/${n}" | dmenu -p "Check" >/dev/null
	jmtpfs --device "${n}" -o allow_other "${MTPT}/${n}" &&
	echo "Mounted: ${MTPT}/${n}" | nfy
else
	umount "${MTPT}/${n}"
	rm -rf "${MTPT}/${n}"
	echo "Unmounted: ${MTPT}/${n}" | nfy
fi
