#!/bin/sh

ffmpeg -y \
	-f x11grab \
	-s 2256x1504 \
	-i :0.0 \
	-r 30 \
	-f oss -i /dev/dsp \
	-c:v libx264 \
	-c:a mp3 \
	${1}
	#-f oss -i /dev/dsp.loop \
	#-filter_complex:a "amix=inputs=2,asetpts=N/SR/TB" \
