#!/bin/sh
xrandr \
	--output DVI-I-0 \
	--mode 1280x1024 \
	--pos 1920x56 \
	--rotate normal \
	--output HDMI-0 \
	--off \
	--output DVI-D-0 \
	--primary \
	--mode 1920x1080 \
	--pos 0x0 \
	--rotate normal
