#!/bin/sh

sjail_init()
{
	echo "
path = \"/usr/local/jail/\${name}\";
host.hostname = \"\${name}\";

exec.clean;
exec.start = \"/bin/sh /etc/rc\";
exec.stop = \"/bin/sh /etc/rc.shutdown\";
allow.mount;
allow.raw_sockets = 1;
mount.devfs;
devfs.ruleset = \"5\";
vnet;
sysvmsg = new;
sysvsem = new;
sysvshm = new;
" >> /etc/jail.conf

	echo "
jail_enable=\"YES\"
jail_parallel_start=\"YES\"
jail_reverse_stop=\"YES\"

if_bridge_load=\"YES\"
if_epair_load=\"YES\"

cloned_interfaces=\"bridge0 epair0\"
ifconfig_bridge0=\"addm re0 addm epair0a up\"
ifconfig_epair0a=\"up\"
" >> /etc/rc.conf

	echo "
[devfsrules_jails=5]
add include \$devfsrules_hide_all
add include \$devfsrules_unhide_basic
add include \$devfsrules_unhide_login
add path 'bpf*' unhide
" >> /etc/devfs.conf

	/etc/netstart
	service devfs restart
}

sjail_new()
{
	local name="${1}"

	echo "
${name} {
	vnet.interface = \"epair0b\";
	exec.start += \"dhclient epair0b\";
}
" >> /etc/jail.conf

	mkdir -p /usr/local/jail
	mkdir -p /usr/local/jail/${name}
	bsdinstall jail /usr/local/jail/${name}
	service jail start ${name}
}

sjail_del()
{
	local name="${1}"

	service jail stop ${name}
	chflags -R noschg /usr/local/jail/${name}
	rm -rf /usr/local/jail/${name}
	sed "/${name} {/,/}/d" /etc/jail.conf
}

usage()
{
	echo "usage: ${0##*/} [-i] [-n jail_name] [-d jail_name]" 1>&2
	exit 1
}

while getopts id:n: arg; do
case "${arg}" in
	i) sjail_init; exit 0 ;;
	d) sjail_del "${OPTARG}"; exit 0 ;;
	n) sjail_new "${OPTARG}"; exit 0 ;;
	*) usage ;;
esac
done

usage
