#!/bin/sh

cmds="\
lock            slock
leave_dwm       kill -TERM $(pidof -s dwm)
reboot          doas reboot
shutdown        doas shutdown -p now"

choice="$(echo "${cmds}" | cut -d ' ' -f 1 | dmenu)" || exit 1
`echo "${cmds}" | grep "^${choice}" | cut -d ' ' -f2-`
