#!/bin/sh

case $1 in
	www)	src="${HOME}/src/margiolis.net/public/"
		dst="master@margiolis.net:/var/www/htdocs/margiolis.net"
		;;
	ftp)	src="${2}"
		dst="master@margiolis.net:/var/www/htdocs/ftp.margiolis.net/${3}"
		;;
	vps)	src="${2}"
		dst="master@margiolis.net:${3}"
		;;
	lap)	src="${2}"
		dst="tpad:${3}"
		;;
	desk)	src="${2}"
		dst="pleb:${3}"
		;;
	*) echo "usage: ${0##*/} {www | ftp | vps | lap | desk} src dst" 1>&2 && exit 1 ;;
esac
test -z "${src}" && echo "${0##*/}: src is empty" 1>&2 && exit 1
test -z "${dst}" && echo "${0##*/}: dest is empty" 1>&2 && exit 1

read -erp "${0##*/}: transfer '${src}' to '${dst}' (y/N)? " act
test "${act}" = "y" && rsync -Purv --delete-after "${src}" "${dst}"
