#!/bin/sh

case "${1}" in
	www)	src="${HOME}/src/margiolis.net/public/"
		dst="master@margiolis.net:/var/www/htdocs/margiolis.net"
		;;
	ftp)	src="${2}"
		dst="master@margiolis.net:/var/www/htdocs/ftp.margiolis.net/${3}"
		;;
	vps)	src="${2}"
		dst="master@margiolis.net:${3}"
		;;
	*)	echo "usage: ${0##*/} {www | ftp | vps} src dst" 1>&2
		exit 1
		;;
esac

read -erp "${0##*/}: transfer '${src}' to '${dst}' (y/N)? " act
test "${act}" = "y" && rsync -Purv --delete-after "${src}" "${dst}"
