#!/bin/sh

QUEUE="${HOME}/shit/queue"
while getopts a:dfv arg; do
case "${arg}" in
        a)      echo "${OPTARG}" >> ${QUEUE}
                exit 0 ;;
        d)      rm ${QUEUE}
                exit 0 ;;
        f)      echo ${QUEUE}
                exit 0 ;;
        v)      cat ${QUEUE} | dmenu -l 30
                exit 0 ;;
        *)      echo "usage: ${0##*/} [-dfv] [-a url]" 1>&2
                exit 1 ;;
esac
done
cat ${QUEUE} | awk '{print $1}' | xargs mpv
