#!/bin/sh

PLAYLIST="${HOME}/shit/playlist"
QUEUE="$(vdq -f)"
while getopts p:q arg; do
case "${arg}" in
        p)      PLAYLIST="${OPTARG}" ;;
        q)      vdq -a "$(cat ${PLAYLIST} | dmenu -l 30)"
                exit 0 ;;
        *)      echo "usage: ${0##*/} [-q] [-p playlist]" 1>&2
                exit 1 ;;
esac
done
cat ${PLAYLIST} | dmenu -l 30 | awk '{print $1}' | xargs mpv
