#!/bin/sh

PLAYLIST="${HOME}/shit/playlist"
while getopts p: arg; do
case "${arg}" in
        p)      PLAYLIST="${OPTARG}" ;;
        *)      echo "usage: ${0##*/} [-p playlist]" 1>&2
                exit 1 ;;
esac
done
mpv $(cat ${PLAYLIST} | dmenu -l 30 | awk '{print $1}')
