#!/bin/sh

usage()
{
	echo "usage: ${0##*/} [-t tap] name" 1>&2
	exit 1
}

tap="tap0"

while getopts t: arg; do
case "${arg}" in
	t) tap="${OPTARG}" ;;
	*) usage ;;
esac
done
shift $((OPTIND - 1))

name="${1}"
test -z "${name}" && usage

ifconfig ${tap} down
bhyvectl --force-poweroff --vm=${name}
bhyvectl --destroy --vm=${name}
