#!/bin/sh

usage()
{
	echo "usage: ${0##*/} [-uv] [-c cpu] [-C com] [-d disksiz] [-g grub_bootdrv]" 1>&2
	echo "               [-G grub_bootdir] [-i img] [-m mem] [-t tap] name" 1>&2
	exit 1
}

err()
{
	echo "${0##*/} ${@}" 1>&2
	exit 1
}

cpu="2"
mem="2G"
disk="disk.img"
tap="tap0"
vnc="no"
uefifile="/usr/local/share/uefi-firmware/BHYVE_UEFI.fd"

# TODO man page?
# TODO merge vmstart and vmstop to `vm <start/stop> ...`? (find new name in this case)
# TODO virtio-blk
# TODO does grub work properly?

while getopts "c:C:d:g:G:i:m:t:uv" arg; do
case "${arg}" in
	c) cpu="${OPTARG}" ;;
	C) com="${OPTARG}" ;;
	d) disksiz="${OPTARG}" ;;
	g) grubdrv="${OPTARG}" ;;
	G) grubdir="${OPTARG}" ;;
	i) img="${OPTARG}" ;;
	m) mem="${OPTARG}" ;;
	t) tap="${OPTARG}" ;;
	u) uefi="-l bootrom,${uefifile}" ;;
	v) vnc="-s 29,fbuf,tcp=0.0.0.0:5900,wait" ;;
	*) usage ;;
esac
done
shift $((OPTIND - 1))

name="${1}"
test -z "${name}" && usage

test ! -f ${uefifile} && \
err "${uefifile} not found. Install $(pkg search uefi-edk | awk '{print $1}')"

ifconfig "${tap}" up || exit 1

test -n "${disksiz}" && truncate -s "${disksiz}" ${disk}

if [ -n "${grubdrv}" ]; then
	echo "(hd0) disk.img" > device.map
	${img:+(cd0) ${img}} >> device.map
	grub-bhyve \
		-m device.map \
		-r ${grubdrv} \
		${grubdir:+-d ${grubdir}} \
		-M ${mem} \
		${name}
fi

bhyve \
	-wHAP \
	-c ${cpu} \
	-m ${mem} \
	-s 0,hostbridge \
	${img:+-s 3,ahci-cd,${img}} \
	-s 4,ahci-hd,${disk} \
	-s 5,virtio-net,${tap} \
	${vnc:+${vnc}} \
	-s 30,xhci,tablet \
	-s 31,lpc \
	${com:+-l com1,${com}} \
	${uefi:+${uefi}} \
	${name}
