#!/bin/sh

bgloc="${HOME}/.local/share/bg"
test -f "${1}" && ln -sf "$(readlink -f "${1}")" "${bgloc}" &&
echo "Changing wallpaper to ${bgloc}" | nfy
xwallpaper --zoom "$(readlink -f "${bgloc}")" >/dev/null
